[workspace]
    default-members=[
        "mxyz-engine",  
    ]
    members = [
        "mxyz-client",
        "mxyz-database",
        "mxyz-engine",
        "mxyz-engine-base",
        "mxyz-network",
        "mxyz-universe",
        "mxyz-server",
        "mxyz-utils",
    ]
