[workspace]
    default-members=[
        "mxyz-engine",  
        # "mxyz-server",
    ]
    members = [
        "mxyz-client",
        "mxyz-database",
        "mxyz-engine",
        "mxyz-server",
        "mxyz-utils",
    ]
