[package]
    name = "mxyz-engine-v2"
    edition = "2018"
    version = "0.1.0"
    authors = [ "Vincent C. Mader <vincent@mader.xyz>" ]

[dependencies]
    mxyz-engine = { path="../mxyz-engine" }
    mxyz-database = { path="../mxyz-database" }
    rayon = "1.5"
