[package]
    name = "mxyz-engine-universe"
    authors = ["Vincent C. Mader <vincent@mader.xyz>"]
    edition = "2018"
    version = "0.1.0"

[dependencies]

[dependencies.serde]
    version = "1.0"
    features = ["derive"]
