[toolchain]
    channel = "nightly-2022-08-11"
        # macOS -> https://rust-lang.github.io/rustup-components-history/aarch64-apple-darwin.html
        # linux -> https://rust-lang.github.io/rustup-components-history/
    components = [ "rustfmt", "rustc-dev" ]
    targets = [ "wasm32-unknown-unknown" ]
    # targets = [ "wasm32-unknown-unknown", "thumbv2-none-eabi" ]
    profile = "minimal"
