[package]
    name = "mxyz-server-engine"
    edition = "2018"
    version = "0.1.0"
    authors = [ "Vincent C. Mader <vincent@mader.xyz>" ]

[dependencies]
    mxyz-engine-universe = { path = "../mxyz-engine-universe" }
